<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/letters/0">Письма</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/senders/0">Отправители</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/transport">Транспорт</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/shortcodes">Шорт-коды</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/log">Журнал</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/queue">Очередь</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/spam_lists">СПАМ-листы</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/fbl">FBL-отчеты</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/mail/settings">Настройки</a></li>