<li><a href="<?= APP::Module('Routing')->root ?>admin/users">Управление</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/roles">Роли</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/oauth/clients">OAuth-клиенты</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/services">Сервисы</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/auth">Аутентификация</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/passwords">Пароли</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/notifications">Уведомления</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/timeouts">Таймауты</a></li>
<li><a href="<?= APP::Module('Routing')->root ?>admin/users/settings">Разное</a></li>